name: paelito # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '1.1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A book reader that tells if the book has been updated. # 79 char long summary
description: |
  Paelito is a book reader that tells if the book has been updated.

  It's source files are written in markdown.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64


parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    build-packages:
      - libwebkit2gtk-4.0-dev
    override-build: |
      set -xe
      go mod download
      go build -o $SNAPCRAFT_PART_INSTALL/bin/maker ./maker
      go build -o $SNAPCRAFT_PART_INSTALL/bin/viewer ./viewer

apps:
  maker:
    command: bin/maker

  paelito:
    command: bin/viewer
    extensions: [gnome-3-34]
    plugs:
      - network-bind
      - network
