name: paelito # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: A book reader that tells if the book has been updated. # 79 char long summary
description: |
  Paelito is a book reader that tells if the book has been updated.

  It's source files are written in markdown.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

base: core20
architectures:
  - build-on: amd64


parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: go
    source: .
    override-build: |
      set -xe
      go mod download
      go build -o $SNAPCRAFT_PART_INSTALL/bin/maker ./maker
      go build -o $SNAPCRAFT_PART_INSTALL/bin/srvr ./srvr
      go build -o $SNAPCRAFT_PART_INSTALL/bin/paelito ./paelito

apps:
  paelito:
    command: bin/paelito
    extensions: [gnome-3-38]


  maker:
    command: bin/maker

  srvr:
    command: bin/srvr
    daemon: simple
    restart-condition: on-abnormal
    plugs:
      - network-bind
      - network
